export type RawCountryData = {
  alpha2: string;
  alpha3: string;
  shortName: string;
  shortNameLowerCase: string;
  fullName: string;
  numericCode: string;
};
const data: RawCountryData[] = [
  {
    alpha2: 'AF',
    shortName: 'AFGHANISTAN',
    shortNameLowerCase: 'Afghanistan',
    fullName: 'the Islamic Republic of Afghanistan',
    alpha3: 'AFG',
    numericCode: '004',
  },
  {
    alpha2: 'AL',
    shortName: 'ALBANIA',
    shortNameLowerCase: 'Albania',
    fullName: 'the Republic of Albania',
    alpha3: 'ALB',
    numericCode: '008',
  },
  {
    alpha2: 'DZ',
    shortName: 'ALGERIA',
    shortNameLowerCase: 'Algeria',
    fullName: "the People's Democratic Republic of Algeria",
    alpha3: 'DZA',
    numericCode: '012',
  },
  {
    alpha2: 'AS',
    shortName: 'AMERICAN SAMOA',
    shortNameLowerCase: 'American Samoa',
    fullName: '',
    alpha3: 'ASM',
    numericCode: '016',
  },
  {
    alpha2: 'AD',
    shortName: 'ANDORRA',
    shortNameLowerCase: 'Andorra',
    fullName: 'the Principality of Andorra',
    alpha3: 'AND',
    numericCode: '020',
  },
  {
    alpha2: 'AO',
    shortName: 'ANGOLA',
    shortNameLowerCase: 'Angola',
    fullName: 'the Republic of Angola',
    alpha3: 'AGO',
    numericCode: '024',
  },
  {
    alpha2: 'AI',
    shortName: 'ANGUILLA',
    shortNameLowerCase: 'Anguilla',
    fullName: '',
    alpha3: 'AIA',
    numericCode: '660',
  },
  {
    alpha2: 'AQ',
    shortName: 'ANTARCTICA',
    shortNameLowerCase: 'Antarctica',
    fullName: '',
    alpha3: 'ATA',
    numericCode: '010',
  },
  {
    alpha2: 'AG',
    shortName: 'ANTIGUA AND BARBUDA',
    shortNameLowerCase: 'Antigua and Barbuda',
    fullName: '',
    alpha3: 'ATG',
    numericCode: '028',
  },
  {
    alpha2: 'AR',
    shortName: 'ARGENTINA',
    shortNameLowerCase: 'Argentina',
    fullName: 'the Argentine Republic',
    alpha3: 'ARG',
    numericCode: '032',
  },
  {
    alpha2: 'AM',
    shortName: 'ARMENIA',
    shortNameLowerCase: 'Armenia',
    fullName: 'the Republic of Armenia',
    alpha3: 'ARM',
    numericCode: '051',
  },
  {
    alpha2: 'AW',
    shortName: 'ARUBA',
    shortNameLowerCase: 'Aruba',
    fullName: '',
    alpha3: 'ABW',
    numericCode: '533',
  },
  {
    alpha2: 'AU',
    shortName: 'AUSTRALIA',
    shortNameLowerCase: 'Australia',
    fullName: '',
    alpha3: 'AUS',
    numericCode: '036',
  },
  {
    alpha2: 'AT',
    shortName: 'AUSTRIA',
    shortNameLowerCase: 'Austria',
    fullName: 'the Republic of Austria',
    alpha3: 'AUT',
    numericCode: '040',
  },
  {
    alpha2: 'AZ',
    shortName: 'AZERBAIJAN',
    shortNameLowerCase: 'Azerbaijan',
    fullName: 'the Republic of Azerbaijan',
    alpha3: 'AZE',
    numericCode: '031',
  },
  {
    alpha2: 'BS',
    shortName: 'BAHAMAS',
    shortNameLowerCase: 'Bahamas (the)',
    fullName: 'the Commonwealth of the Bahamas',
    alpha3: 'BHS',
    numericCode: '044',
  },
  {
    alpha2: 'BH',
    shortName: 'BAHRAIN',
    shortNameLowerCase: 'Bahrain',
    fullName: 'the Kingdom of Bahrain',
    alpha3: 'BHR',
    numericCode: '048',
  },
  {
    alpha2: 'BD',
    shortName: 'BANGLADESH',
    shortNameLowerCase: 'Bangladesh',
    fullName: "the People's Republic of Bangladesh",
    alpha3: 'BGD',
    numericCode: '050',
  },
  {
    alpha2: 'BB',
    shortName: 'BARBADOS',
    shortNameLowerCase: 'Barbados',
    fullName: '',
    alpha3: 'BRB',
    numericCode: '052',
  },
  {
    alpha2: 'BY',
    shortName: 'BELARUS',
    shortNameLowerCase: 'Belarus',
    fullName: 'the Republic of Belarus',
    alpha3: 'BLR',
    numericCode: '112',
  },
  {
    alpha2: 'BE',
    shortName: 'BELGIUM',
    shortNameLowerCase: 'Belgium',
    fullName: 'the Kingdom of Belgium',
    alpha3: 'BEL',
    numericCode: '056',
  },
  {
    alpha2: 'BZ',
    shortName: 'BELIZE',
    shortNameLowerCase: 'Belize',
    fullName: '',
    alpha3: 'BLZ',
    numericCode: '084',
  },
  {
    alpha2: 'BJ',
    shortName: 'BENIN',
    shortNameLowerCase: 'Benin',
    fullName: 'the Republic of Benin',
    alpha3: 'BEN',
    numericCode: '204',
  },
  {
    alpha2: 'BM',
    shortName: 'BERMUDA',
    shortNameLowerCase: 'Bermuda',
    fullName: '',
    alpha3: 'BMU',
    numericCode: '060',
  },
  {
    alpha2: 'AX',
    shortName: 'ÅLAND ISLANDS',
    shortNameLowerCase: 'Åland Islands',
    fullName: '',
    alpha3: 'ALA',
    numericCode: '248',
  },
  {
    alpha2: 'BT',
    shortName: 'BHUTAN',
    shortNameLowerCase: 'Bhutan',
    fullName: 'the Kingdom of Bhutan',
    alpha3: 'BTN',
    numericCode: '064',
  },
  {
    alpha2: 'BO',
    shortName: 'BOLIVIA (PLURINATIONAL STATE OF)',
    shortNameLowerCase: 'Bolivia (Plurinational State of)',
    fullName: 'the Plurinational State of Bolivia',
    alpha3: 'BOL',
    numericCode: '068',
  },
  {
    alpha2: 'BQ',
    shortName: 'BONAIRE, SINT EUSTATIUS AND SABA',
    shortNameLowerCase: 'Bonaire, Sint Eustatius and Saba',
    fullName: '',
    alpha3: 'BES',
    numericCode: '535',
  },
  {
    alpha2: 'BA',
    shortName: 'BOSNIA AND HERZEGOVINA',
    shortNameLowerCase: 'Bosnia and Herzegovina',
    fullName: '',
    alpha3: 'BIH',
    numericCode: '070',
  },
  {
    alpha2: 'BW',
    shortName: 'BOTSWANA',
    shortNameLowerCase: 'Botswana',
    fullName: 'the Republic of Botswana',
    alpha3: 'BWA',
    numericCode: '072',
  },
  {
    alpha2: 'BV',
    shortName: 'BOUVET ISLAND',
    shortNameLowerCase: 'Bouvet Island',
    fullName: '',
    alpha3: 'BVT',
    numericCode: '074',
  },
  {
    alpha2: 'BR',
    shortName: 'BRAZIL',
    shortNameLowerCase: 'Brazil',
    fullName: 'the Federative Republic of Brazil',
    alpha3: 'BRA',
    numericCode: '076',
  },
  {
    alpha2: 'IO',
    shortName: 'BRITISH INDIAN OCEAN TERRITORY',
    shortNameLowerCase: 'British Indian Ocean Territory (the)',
    fullName: '',
    alpha3: 'IOT',
    numericCode: '086',
  },
  {
    alpha2: 'BN',
    shortName: 'BRUNEI DARUSSALAM',
    shortNameLowerCase: 'Brunei Darussalam',
    fullName: '',
    alpha3: 'BRN',
    numericCode: '096',
  },
  {
    alpha2: 'BG',
    shortName: 'BULGARIA',
    shortNameLowerCase: 'Bulgaria',
    fullName: 'the Republic of Bulgaria',
    alpha3: 'BGR',
    numericCode: '100',
  },
  {
    alpha2: 'BF',
    shortName: 'BURKINA FASO',
    shortNameLowerCase: 'Burkina Faso',
    fullName: '',
    alpha3: 'BFA',
    numericCode: '854',
  },
  {
    alpha2: 'BI',
    shortName: 'BURUNDI',
    shortNameLowerCase: 'Burundi',
    fullName: 'the Republic of Burundi',
    alpha3: 'BDI',
    numericCode: '108',
  },
  {
    alpha2: 'CV',
    shortName: 'CABO VERDE',
    shortNameLowerCase: 'Cabo Verde',
    fullName: 'the Republic of Cabo Verde',
    alpha3: 'CPV',
    numericCode: '132',
  },
  {
    alpha2: 'KH',
    shortName: 'CAMBODIA',
    shortNameLowerCase: 'Cambodia',
    fullName: 'the Kingdom of Cambodia',
    alpha3: 'KHM',
    numericCode: '116',
  },
  {
    alpha2: 'CM',
    shortName: 'CAMEROON',
    shortNameLowerCase: 'Cameroon',
    fullName: 'the Republic of Cameroon',
    alpha3: 'CMR',
    numericCode: '120',
  },
  {
    alpha2: 'CA',
    shortName: 'CANADA',
    shortNameLowerCase: 'Canada',
    fullName: '',
    alpha3: 'CAN',
    numericCode: '124',
  },
  {
    alpha2: 'KY',
    shortName: 'CAYMAN ISLANDS',
    shortNameLowerCase: 'Cayman Islands (the)',
    fullName: '',
    alpha3: 'CYM',
    numericCode: '136',
  },
  {
    alpha2: 'CF',
    shortName: 'CENTRAL AFRICAN REPUBLIC',
    shortNameLowerCase: 'Central African Republic (the)',
    fullName: 'the Central African Republic',
    alpha3: 'CAF',
    numericCode: '140',
  },
  {
    alpha2: 'TD',
    shortName: 'CHAD',
    shortNameLowerCase: 'Chad',
    fullName: 'the Republic of Chad',
    alpha3: 'TCD',
    numericCode: '148',
  },
  {
    alpha2: 'CL',
    shortName: 'CHILE',
    shortNameLowerCase: 'Chile',
    fullName: 'the Republic of Chile',
    alpha3: 'CHL',
    numericCode: '152',
  },
  {
    alpha2: 'CN',
    shortName: 'CHINA',
    shortNameLowerCase: 'China',
    fullName: "the People's Republic of China",
    alpha3: 'CHN',
    numericCode: '156',
  },
  {
    alpha2: 'CX',
    shortName: 'CHRISTMAS ISLAND',
    shortNameLowerCase: 'Christmas Island',
    fullName: '',
    alpha3: 'CXR',
    numericCode: '162',
  },
  {
    alpha2: 'CC',
    shortName: 'COCOS (KEELING) ISLANDS',
    shortNameLowerCase: 'Cocos (Keeling) Islands (the)',
    fullName: '',
    alpha3: 'CCK',
    numericCode: '166',
  },
  {
    alpha2: 'CO',
    shortName: 'COLOMBIA',
    shortNameLowerCase: 'Colombia',
    fullName: 'the Republic of Colombia',
    alpha3: 'COL',
    numericCode: '170',
  },
  {
    alpha2: 'KM',
    shortName: 'COMOROS',
    shortNameLowerCase: 'Comoros (the)',
    fullName: 'the Union of the Comoros',
    alpha3: 'COM',
    numericCode: '174',
  },
  {
    alpha2: 'CD',
    shortName: 'CONGO, DEMOCRATIC REPUBLIC OF THE',
    shortNameLowerCase: 'Congo (the Democratic Republic of the)',
    fullName: 'the Democratic Republic of the Congo',
    alpha3: 'COD',
    numericCode: '180',
  },
  {
    alpha2: 'CG',
    shortName: 'CONGO',
    shortNameLowerCase: 'Congo (the)',
    fullName: 'the Republic of the Congo',
    alpha3: 'COG',
    numericCode: '178',
  },
  {
    alpha2: 'CK',
    shortName: 'COOK ISLANDS',
    shortNameLowerCase: 'Cook Islands (the)',
    fullName: '',
    alpha3: 'COK',
    numericCode: '184',
  },
  {
    alpha2: 'CR',
    shortName: 'COSTA RICA',
    shortNameLowerCase: 'Costa Rica',
    fullName: 'the Republic of Costa Rica',
    alpha3: 'CRI',
    numericCode: '188',
  },
  {
    alpha2: 'HR',
    shortName: 'CROATIA',
    shortNameLowerCase: 'Croatia',
    fullName: 'the Republic of Croatia',
    alpha3: 'HRV',
    numericCode: '191',
  },
  {
    alpha2: 'CU',
    shortName: 'CUBA',
    shortNameLowerCase: 'Cuba',
    fullName: 'the Republic of Cuba',
    alpha3: 'CUB',
    numericCode: '192',
  },
  {
    alpha2: 'CW',
    shortName: 'CURAÇAO',
    shortNameLowerCase: 'Curaçao',
    fullName: '',
    alpha3: 'CUW',
    numericCode: '531',
  },
  {
    alpha2: 'CY',
    shortName: 'CYPRUS',
    shortNameLowerCase: 'Cyprus',
    fullName: 'the Republic of Cyprus',
    alpha3: 'CYP',
    numericCode: '196',
  },
  {
    alpha2: 'CZ',
    shortName: 'CZECHIA',
    shortNameLowerCase: 'Czechia',
    fullName: 'the Czech Republic',
    alpha3: 'CZE',
    numericCode: '203',
  },
  {
    alpha2: 'CI',
    shortName: "CÔTE D'IVOIRE",
    shortNameLowerCase: "Côte d'Ivoire",
    fullName: "the Republic of Côte d'Ivoire",
    alpha3: 'CIV',
    numericCode: '384',
  },
  {
    alpha2: 'DK',
    shortName: 'DENMARK',
    shortNameLowerCase: 'Denmark',
    fullName: 'the Kingdom of Denmark',
    alpha3: 'DNK',
    numericCode: '208',
  },
  {
    alpha2: 'DJ',
    shortName: 'DJIBOUTI',
    shortNameLowerCase: 'Djibouti',
    fullName: 'the Republic of Djibouti',
    alpha3: 'DJI',
    numericCode: '262',
  },
  {
    alpha2: 'DM',
    shortName: 'DOMINICA',
    shortNameLowerCase: 'Dominica',
    fullName: 'the Commonwealth of Dominica',
    alpha3: 'DMA',
    numericCode: '212',
  },
  {
    alpha2: 'DO',
    shortName: 'DOMINICAN REPUBLIC',
    shortNameLowerCase: 'Dominican Republic (the)',
    fullName: 'the Dominican Republic',
    alpha3: 'DOM',
    numericCode: '214',
  },
  {
    alpha2: 'EC',
    shortName: 'ECUADOR',
    shortNameLowerCase: 'Ecuador',
    fullName: 'the Republic of Ecuador',
    alpha3: 'ECU',
    numericCode: '218',
  },
  {
    alpha2: 'EG',
    shortName: 'EGYPT',
    shortNameLowerCase: 'Egypt',
    fullName: 'the Arab Republic of Egypt',
    alpha3: 'EGY',
    numericCode: '818',
  },
  {
    alpha2: 'SV',
    shortName: 'EL SALVADOR',
    shortNameLowerCase: 'El Salvador',
    fullName: 'the Republic of El Salvador',
    alpha3: 'SLV',
    numericCode: '222',
  },
  {
    alpha2: 'GQ',
    shortName: 'EQUATORIAL GUINEA',
    shortNameLowerCase: 'Equatorial Guinea',
    fullName: 'the Republic of Equatorial Guinea',
    alpha3: 'GNQ',
    numericCode: '226',
  },
  {
    alpha2: 'ER',
    shortName: 'ERITREA',
    shortNameLowerCase: 'Eritrea',
    fullName: 'the State of Eritrea',
    alpha3: 'ERI',
    numericCode: '232',
  },
  {
    alpha2: 'EE',
    shortName: 'ESTONIA',
    shortNameLowerCase: 'Estonia',
    fullName: 'the Republic of Estonia',
    alpha3: 'EST',
    numericCode: '233',
  },
  {
    alpha2: 'SZ',
    shortName: 'ESWATINI',
    shortNameLowerCase: 'Eswatini',
    fullName: 'the Kingdom of Eswatini',
    alpha3: 'SWZ',
    numericCode: '748',
  },
  {
    alpha2: 'ET',
    shortName: 'ETHIOPIA',
    shortNameLowerCase: 'Ethiopia',
    fullName: 'the Federal Democratic Republic of Ethiopia',
    alpha3: 'ETH',
    numericCode: '231',
  },
  {
    alpha2: 'FK',
    shortName: 'FALKLAND ISLANDS (MALVINAS)',
    shortNameLowerCase: 'Falkland Islands (the) [Malvinas]',
    fullName: '',
    alpha3: 'FLK',
    numericCode: '238',
  },
  {
    alpha2: 'FO',
    shortName: 'FAROE ISLANDS',
    shortNameLowerCase: 'Faroe Islands (the)',
    fullName: '',
    alpha3: 'FRO',
    numericCode: '234',
  },
  {
    alpha2: 'FJ',
    shortName: 'FIJI',
    shortNameLowerCase: 'Fiji',
    fullName: 'the Republic of Fiji',
    alpha3: 'FJI',
    numericCode: '242',
  },
  {
    alpha2: 'FI',
    shortName: 'FINLAND',
    shortNameLowerCase: 'Finland',
    fullName: 'the Republic of Finland',
    alpha3: 'FIN',
    numericCode: '246',
  },
  {
    alpha2: 'FR',
    shortName: 'FRANCE',
    shortNameLowerCase: 'France',
    fullName: 'the French Republic',
    alpha3: 'FRA',
    numericCode: '250',
  },
  {
    alpha2: 'GF',
    shortName: 'FRENCH GUIANA',
    shortNameLowerCase: 'French Guiana',
    fullName: '',
    alpha3: 'GUF',
    numericCode: '254',
  },
  {
    alpha2: 'PF',
    shortName: 'FRENCH POLYNESIA',
    shortNameLowerCase: 'French Polynesia',
    fullName: '',
    alpha3: 'PYF',
    numericCode: '258',
  },
  {
    alpha2: 'TF',
    shortName: 'FRENCH SOUTHERN TERRITORIES',
    shortNameLowerCase: 'French Southern Territories (the)',
    fullName: '',
    alpha3: 'ATF',
    numericCode: '260',
  },
  {
    alpha2: 'GA',
    shortName: 'GABON',
    shortNameLowerCase: 'Gabon',
    fullName: 'the Gabonese Republic',
    alpha3: 'GAB',
    numericCode: '266',
  },
  {
    alpha2: 'GM',
    shortName: 'GAMBIA',
    shortNameLowerCase: 'Gambia (the)',
    fullName: 'the Republic of the Gambia',
    alpha3: 'GMB',
    numericCode: '270',
  },
  {
    alpha2: 'GE',
    shortName: 'GEORGIA',
    shortNameLowerCase: 'Georgia',
    fullName: '',
    alpha3: 'GEO',
    numericCode: '268',
  },
  {
    alpha2: 'DE',
    shortName: 'GERMANY',
    shortNameLowerCase: 'Germany',
    fullName: 'the Federal Republic of Germany',
    alpha3: 'DEU',
    numericCode: '276',
  },
  {
    alpha2: 'GH',
    shortName: 'GHANA',
    shortNameLowerCase: 'Ghana',
    fullName: 'the Republic of Ghana',
    alpha3: 'GHA',
    numericCode: '288',
  },
  {
    alpha2: 'GI',
    shortName: 'GIBRALTAR',
    shortNameLowerCase: 'Gibraltar',
    fullName: '',
    alpha3: 'GIB',
    numericCode: '292',
  },
  {
    alpha2: 'GR',
    shortName: 'GREECE',
    shortNameLowerCase: 'Greece',
    fullName: 'the Hellenic Republic',
    alpha3: 'GRC',
    numericCode: '300',
  },
  {
    alpha2: 'GL',
    shortName: 'GREENLAND',
    shortNameLowerCase: 'Greenland',
    fullName: '',
    alpha3: 'GRL',
    numericCode: '304',
  },
  {
    alpha2: 'GD',
    shortName: 'GRENADA',
    shortNameLowerCase: 'Grenada',
    fullName: '',
    alpha3: 'GRD',
    numericCode: '308',
  },
  {
    alpha2: 'GP',
    shortName: 'GUADELOUPE',
    shortNameLowerCase: 'Guadeloupe',
    fullName: '',
    alpha3: 'GLP',
    numericCode: '312',
  },
  {
    alpha2: 'GU',
    shortName: 'GUAM',
    shortNameLowerCase: 'Guam',
    fullName: '',
    alpha3: 'GUM',
    numericCode: '316',
  },
  {
    alpha2: 'GT',
    shortName: 'GUATEMALA',
    shortNameLowerCase: 'Guatemala',
    fullName: 'the Republic of Guatemala',
    alpha3: 'GTM',
    numericCode: '320',
  },
  {
    alpha2: 'GG',
    shortName: 'GUERNSEY',
    shortNameLowerCase: 'Guernsey',
    fullName: '',
    alpha3: 'GGY',
    numericCode: '831',
  },
  {
    alpha2: 'GN',
    shortName: 'GUINEA',
    shortNameLowerCase: 'Guinea',
    fullName: 'the Republic of Guinea',
    alpha3: 'GIN',
    numericCode: '324',
  },
  {
    alpha2: 'GW',
    shortName: 'GUINEA-BISSAU',
    shortNameLowerCase: 'Guinea-Bissau',
    fullName: 'the Republic of Guinea-Bissau',
    alpha3: 'GNB',
    numericCode: '624',
  },
  {
    alpha2: 'GY',
    shortName: 'GUYANA',
    shortNameLowerCase: 'Guyana',
    fullName: 'the Co-operative Republic of Guyana',
    alpha3: 'GUY',
    numericCode: '328',
  },
  {
    alpha2: 'HT',
    shortName: 'HAITI',
    shortNameLowerCase: 'Haiti',
    fullName: 'the Republic of Haiti',
    alpha3: 'HTI',
    numericCode: '332',
  },
  {
    alpha2: 'HM',
    shortName: 'HEARD ISLAND AND MCDONALD ISLANDS',
    shortNameLowerCase: 'Heard Island and McDonald Islands',
    fullName: '',
    alpha3: 'HMD',
    numericCode: '334',
  },
  {
    alpha2: 'VA',
    shortName: 'HOLY SEE',
    shortNameLowerCase: 'Holy See (the)',
    fullName: '',
    alpha3: 'VAT',
    numericCode: '336',
  },
  {
    alpha2: 'HN',
    shortName: 'HONDURAS',
    shortNameLowerCase: 'Honduras',
    fullName: 'the Republic of Honduras',
    alpha3: 'HND',
    numericCode: '340',
  },
  {
    alpha2: 'HK',
    shortName: 'HONG KONG',
    shortNameLowerCase: 'Hong Kong',
    fullName: 'the Hong Kong Special Administrative Region of China',
    alpha3: 'HKG',
    numericCode: '344',
  },
  {
    alpha2: 'HU',
    shortName: 'HUNGARY',
    shortNameLowerCase: 'Hungary',
    fullName: '',
    alpha3: 'HUN',
    numericCode: '348',
  },
  {
    alpha2: 'IS',
    shortName: 'ICELAND',
    shortNameLowerCase: 'Iceland',
    fullName: 'the Republic of Iceland',
    alpha3: 'ISL',
    numericCode: '352',
  },
  {
    alpha2: 'IN',
    shortName: 'INDIA',
    shortNameLowerCase: 'India',
    fullName: 'the Republic of India',
    alpha3: 'IND',
    numericCode: '356',
  },
  {
    alpha2: 'ID',
    shortName: 'INDONESIA',
    shortNameLowerCase: 'Indonesia',
    fullName: 'the Republic of Indonesia',
    alpha3: 'IDN',
    numericCode: '360',
  },
  {
    alpha2: 'IR',
    shortName: 'IRAN (ISLAMIC REPUBLIC OF)',
    shortNameLowerCase: 'Iran (Islamic Republic of)',
    fullName: 'the Islamic Republic of Iran',
    alpha3: 'IRN',
    numericCode: '364',
  },
  {
    alpha2: 'IQ',
    shortName: 'IRAQ',
    shortNameLowerCase: 'Iraq',
    fullName: 'the Republic of Iraq',
    alpha3: 'IRQ',
    numericCode: '368',
  },
  {
    alpha2: 'IE',
    shortName: 'IRELAND',
    shortNameLowerCase: 'Ireland',
    fullName: '',
    alpha3: 'IRL',
    numericCode: '372',
  },
  {
    alpha2: 'IM',
    shortName: 'ISLE OF MAN',
    shortNameLowerCase: 'Isle of Man',
    fullName: '',
    alpha3: 'IMN',
    numericCode: '833',
  },
  {
    alpha2: 'IL',
    shortName: 'ISRAEL',
    shortNameLowerCase: 'Israel',
    fullName: 'the State of Israel',
    alpha3: 'ISR',
    numericCode: '376',
  },
  {
    alpha2: 'IT',
    shortName: 'ITALY',
    shortNameLowerCase: 'Italy',
    fullName: 'the Republic of Italy',
    alpha3: 'ITA',
    numericCode: '380',
  },
  {
    alpha2: 'JM',
    shortName: 'JAMAICA',
    shortNameLowerCase: 'Jamaica',
    fullName: '',
    alpha3: 'JAM',
    numericCode: '388',
  },
  {
    alpha2: 'JP',
    shortName: 'JAPAN',
    shortNameLowerCase: 'Japan',
    fullName: '',
    alpha3: 'JPN',
    numericCode: '392',
  },
  {
    alpha2: 'JE',
    shortName: 'JERSEY',
    shortNameLowerCase: 'Jersey',
    fullName: '',
    alpha3: 'JEY',
    numericCode: '832',
  },
  {
    alpha2: 'JO',
    shortName: 'JORDAN',
    shortNameLowerCase: 'Jordan',
    fullName: 'the Hashemite Kingdom of Jordan',
    alpha3: 'JOR',
    numericCode: '400',
  },
  {
    alpha2: 'KZ',
    shortName: 'KAZAKHSTAN',
    shortNameLowerCase: 'Kazakhstan',
    fullName: 'the Republic of Kazakhstan',
    alpha3: 'KAZ',
    numericCode: '398',
  },
  {
    alpha2: 'KE',
    shortName: 'KENYA',
    shortNameLowerCase: 'Kenya',
    fullName: 'the Republic of Kenya',
    alpha3: 'KEN',
    numericCode: '404',
  },
  {
    alpha2: 'KI',
    shortName: 'KIRIBATI',
    shortNameLowerCase: 'Kiribati',
    fullName: 'the Republic of Kiribati',
    alpha3: 'KIR',
    numericCode: '296',
  },
  {
    alpha2: 'KP',
    shortName: "KOREA (DEMOCRATIC PEOPLE'S REPUBLIC OF)",
    shortNameLowerCase: "Korea (the Democratic People's Republic of)",
    fullName: "the Democratic People's Republic of Korea",
    alpha3: 'PRK',
    numericCode: '408',
  },
  {
    alpha2: 'KR',
    shortName: 'KOREA, REPUBLIC OF',
    shortNameLowerCase: 'Korea (the Republic of)',
    fullName: 'the Republic of Korea',
    alpha3: 'KOR',
    numericCode: '410',
  },
  {
    alpha2: 'KW',
    shortName: 'KUWAIT',
    shortNameLowerCase: 'Kuwait',
    fullName: 'the State of Kuwait',
    alpha3: 'KWT',
    numericCode: '414',
  },
  {
    alpha2: 'KG',
    shortName: 'KYRGYZSTAN',
    shortNameLowerCase: 'Kyrgyzstan',
    fullName: 'the Kyrgyz Republic',
    alpha3: 'KGZ',
    numericCode: '417',
  },
  {
    alpha2: 'LA',
    shortName: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    shortNameLowerCase: "Lao People's Democratic Republic (the)",
    fullName: "the Lao People's Democratic Republic",
    alpha3: 'LAO',
    numericCode: '418',
  },
  {
    alpha2: 'LV',
    shortName: 'LATVIA',
    shortNameLowerCase: 'Latvia',
    fullName: 'the Republic of Latvia',
    alpha3: 'LVA',
    numericCode: '428',
  },
  {
    alpha2: 'LB',
    shortName: 'LEBANON',
    shortNameLowerCase: 'Lebanon',
    fullName: 'the Lebanese Republic',
    alpha3: 'LBN',
    numericCode: '422',
  },
  {
    alpha2: 'LS',
    shortName: 'LESOTHO',
    shortNameLowerCase: 'Lesotho',
    fullName: 'the Kingdom of Lesotho',
    alpha3: 'LSO',
    numericCode: '426',
  },
  {
    alpha2: 'LR',
    shortName: 'LIBERIA',
    shortNameLowerCase: 'Liberia',
    fullName: 'the Republic of Liberia',
    alpha3: 'LBR',
    numericCode: '430',
  },
  {
    alpha2: 'LY',
    shortName: 'LIBYA',
    shortNameLowerCase: 'Libya',
    fullName: 'the State of Libya',
    alpha3: 'LBY',
    numericCode: '434',
  },
  {
    alpha2: 'LI',
    shortName: 'LIECHTENSTEIN',
    shortNameLowerCase: 'Liechtenstein',
    fullName: 'the Principality of Liechtenstein',
    alpha3: 'LIE',
    numericCode: '438',
  },
  {
    alpha2: 'LT',
    shortName: 'LITHUANIA',
    shortNameLowerCase: 'Lithuania',
    fullName: 'the Republic of Lithuania',
    alpha3: 'LTU',
    numericCode: '440',
  },
  {
    alpha2: 'LU',
    shortName: 'LUXEMBOURG',
    shortNameLowerCase: 'Luxembourg',
    fullName: 'the Grand Duchy of Luxembourg',
    alpha3: 'LUX',
    numericCode: '442',
  },
  {
    alpha2: 'MO',
    shortName: 'MACAO',
    shortNameLowerCase: 'Macao',
    fullName: 'Macao Special Administrative Region of China',
    alpha3: 'MAC',
    numericCode: '446',
  },
  {
    alpha2: 'MG',
    shortName: 'MADAGASCAR',
    shortNameLowerCase: 'Madagascar',
    fullName: 'the Republic of Madagascar',
    alpha3: 'MDG',
    numericCode: '450',
  },
  {
    alpha2: 'MW',
    shortName: 'MALAWI',
    shortNameLowerCase: 'Malawi',
    fullName: 'the Republic of Malawi',
    alpha3: 'MWI',
    numericCode: '454',
  },
  {
    alpha2: 'MY',
    shortName: 'MALAYSIA',
    shortNameLowerCase: 'Malaysia',
    fullName: '',
    alpha3: 'MYS',
    numericCode: '458',
  },
  {
    alpha2: 'MV',
    shortName: 'MALDIVES',
    shortNameLowerCase: 'Maldives',
    fullName: 'the Republic of Maldives',
    alpha3: 'MDV',
    numericCode: '462',
  },
  {
    alpha2: 'ML',
    shortName: 'MALI',
    shortNameLowerCase: 'Mali',
    fullName: 'the Republic of Mali',
    alpha3: 'MLI',
    numericCode: '466',
  },
  {
    alpha2: 'MT',
    shortName: 'MALTA',
    shortNameLowerCase: 'Malta',
    fullName: 'the Republic of Malta',
    alpha3: 'MLT',
    numericCode: '470',
  },
  {
    alpha2: 'MH',
    shortName: 'MARSHALL ISLANDS',
    shortNameLowerCase: 'Marshall Islands (the)',
    fullName: 'the Republic of the Marshall Islands',
    alpha3: 'MHL',
    numericCode: '584',
  },
  {
    alpha2: 'MQ',
    shortName: 'MARTINIQUE',
    shortNameLowerCase: 'Martinique',
    fullName: '',
    alpha3: 'MTQ',
    numericCode: '474',
  },
  {
    alpha2: 'MR',
    shortName: 'MAURITANIA',
    shortNameLowerCase: 'Mauritania',
    fullName: 'the Islamic Republic of Mauritania',
    alpha3: 'MRT',
    numericCode: '478',
  },
  {
    alpha2: 'MU',
    shortName: 'MAURITIUS',
    shortNameLowerCase: 'Mauritius',
    fullName: 'the Republic of Mauritius',
    alpha3: 'MUS',
    numericCode: '480',
  },
  {
    alpha2: 'YT',
    shortName: 'MAYOTTE',
    shortNameLowerCase: 'Mayotte',
    fullName: '',
    alpha3: 'MYT',
    numericCode: '175',
  },
  {
    alpha2: 'MX',
    shortName: 'MEXICO',
    shortNameLowerCase: 'Mexico',
    fullName: 'the United Mexican States',
    alpha3: 'MEX',
    numericCode: '484',
  },
  {
    alpha2: 'FM',
    shortName: 'MICRONESIA (FEDERATED STATES OF)',
    shortNameLowerCase: 'Micronesia (Federated States of)',
    fullName: 'the Federated States of Micronesia',
    alpha3: 'FSM',
    numericCode: '583',
  },
  {
    alpha2: 'MD',
    shortName: 'MOLDOVA, REPUBLIC OF',
    shortNameLowerCase: 'Moldova (the Republic of)',
    fullName: 'the Republic of Moldova',
    alpha3: 'MDA',
    numericCode: '498',
  },
  {
    alpha2: 'MC',
    shortName: 'MONACO',
    shortNameLowerCase: 'Monaco',
    fullName: 'the Principality of Monaco',
    alpha3: 'MCO',
    numericCode: '492',
  },
  {
    alpha2: 'MN',
    shortName: 'MONGOLIA',
    shortNameLowerCase: 'Mongolia',
    fullName: '',
    alpha3: 'MNG',
    numericCode: '496',
  },
  {
    alpha2: 'ME',
    shortName: 'MONTENEGRO',
    shortNameLowerCase: 'Montenegro',
    fullName: '',
    alpha3: 'MNE',
    numericCode: '499',
  },
  {
    alpha2: 'MS',
    shortName: 'MONTSERRAT',
    shortNameLowerCase: 'Montserrat',
    fullName: '',
    alpha3: 'MSR',
    numericCode: '500',
  },
  {
    alpha2: 'MA',
    shortName: 'MOROCCO',
    shortNameLowerCase: 'Morocco',
    fullName: 'the Kingdom of Morocco',
    alpha3: 'MAR',
    numericCode: '504',
  },
  {
    alpha2: 'MZ',
    shortName: 'MOZAMBIQUE',
    shortNameLowerCase: 'Mozambique',
    fullName: 'the Republic of Mozambique',
    alpha3: 'MOZ',
    numericCode: '508',
  },
  {
    alpha2: 'MM',
    shortName: 'MYANMAR',
    shortNameLowerCase: 'Myanmar',
    fullName: 'the Republic of the Union of Myanmar',
    alpha3: 'MMR',
    numericCode: '104',
  },
  {
    alpha2: 'NA',
    shortName: 'NAMIBIA',
    shortNameLowerCase: 'Namibia',
    fullName: 'the Republic of Namibia',
    alpha3: 'NAM',
    numericCode: '516',
  },
  {
    alpha2: 'NR',
    shortName: 'NAURU',
    shortNameLowerCase: 'Nauru',
    fullName: 'the Republic of Nauru',
    alpha3: 'NRU',
    numericCode: '520',
  },
  {
    alpha2: 'NP',
    shortName: 'NEPAL',
    shortNameLowerCase: 'Nepal',
    fullName: '',
    alpha3: 'NPL',
    numericCode: '524',
  },
  {
    alpha2: 'NL',
    shortName: 'NETHERLANDS',
    shortNameLowerCase: 'Netherlands (the)',
    fullName: 'the Kingdom of the Netherlands',
    alpha3: 'NLD',
    numericCode: '528',
  },
  {
    alpha2: 'NC',
    shortName: 'NEW CALEDONIA',
    shortNameLowerCase: 'New Caledonia',
    fullName: '',
    alpha3: 'NCL',
    numericCode: '540',
  },
  {
    alpha2: 'NZ',
    shortName: 'NEW ZEALAND',
    shortNameLowerCase: 'New Zealand',
    fullName: '',
    alpha3: 'NZL',
    numericCode: '554',
  },
  {
    alpha2: 'NI',
    shortName: 'NICARAGUA',
    shortNameLowerCase: 'Nicaragua',
    fullName: 'the Republic of Nicaragua',
    alpha3: 'NIC',
    numericCode: '558',
  },
  {
    alpha2: 'NE',
    shortName: 'NIGER',
    shortNameLowerCase: 'Niger (the)',
    fullName: 'the Republic of the Niger',
    alpha3: 'NER',
    numericCode: '562',
  },
  {
    alpha2: 'NG',
    shortName: 'NIGERIA',
    shortNameLowerCase: 'Nigeria',
    fullName: 'the Federal Republic of Nigeria',
    alpha3: 'NGA',
    numericCode: '566',
  },
  {
    alpha2: 'NU',
    shortName: 'NIUE',
    shortNameLowerCase: 'Niue',
    fullName: '',
    alpha3: 'NIU',
    numericCode: '570',
  },
  {
    alpha2: 'NF',
    shortName: 'NORFOLK ISLAND',
    shortNameLowerCase: 'Norfolk Island',
    fullName: '',
    alpha3: 'NFK',
    numericCode: '574',
  },
  {
    alpha2: 'MK',
    shortName: 'NORTH MACEDONIA',
    shortNameLowerCase: 'North Macedonia',
    fullName: 'the Republic of North Macedonia',
    alpha3: 'MKD',
    numericCode: '807',
  },
  {
    alpha2: 'MP',
    shortName: 'NORTHERN MARIANA ISLANDS',
    shortNameLowerCase: 'Northern Mariana Islands (the)',
    fullName: 'the Commonwealth of the Northern Mariana Islands',
    alpha3: 'MNP',
    numericCode: '580',
  },
  {
    alpha2: 'NO',
    shortName: 'NORWAY',
    shortNameLowerCase: 'Norway',
    fullName: 'the Kingdom of Norway',
    alpha3: 'NOR',
    numericCode: '578',
  },
  {
    alpha2: 'OM',
    shortName: 'OMAN',
    shortNameLowerCase: 'Oman',
    fullName: 'the Sultanate of Oman',
    alpha3: 'OMN',
    numericCode: '512',
  },
  {
    alpha2: 'PK',
    shortName: 'PAKISTAN',
    shortNameLowerCase: 'Pakistan',
    fullName: 'the Islamic Republic of Pakistan',
    alpha3: 'PAK',
    numericCode: '586',
  },
  {
    alpha2: 'PW',
    shortName: 'PALAU',
    shortNameLowerCase: 'Palau',
    fullName: 'the Republic of Palau',
    alpha3: 'PLW',
    numericCode: '585',
  },
  {
    alpha2: 'PS',
    shortName: 'PALESTINE, STATE OF',
    shortNameLowerCase: 'Palestine, State of',
    fullName: 'the State of Palestine',
    alpha3: 'PSE',
    numericCode: '275',
  },
  {
    alpha2: 'PA',
    shortName: 'PANAMA',
    shortNameLowerCase: 'Panama',
    fullName: 'the Republic of Panama',
    alpha3: 'PAN',
    numericCode: '591',
  },
  {
    alpha2: 'PG',
    shortName: 'PAPUA NEW GUINEA',
    shortNameLowerCase: 'Papua New Guinea',
    fullName: 'the Independent State of Papua New Guinea',
    alpha3: 'PNG',
    numericCode: '598',
  },
  {
    alpha2: 'PY',
    shortName: 'PARAGUAY',
    shortNameLowerCase: 'Paraguay',
    fullName: 'the Republic of Paraguay',
    alpha3: 'PRY',
    numericCode: '600',
  },
  {
    alpha2: 'PE',
    shortName: 'PERU',
    shortNameLowerCase: 'Peru',
    fullName: 'the Republic of Peru',
    alpha3: 'PER',
    numericCode: '604',
  },
  {
    alpha2: 'PH',
    shortName: 'PHILIPPINES',
    shortNameLowerCase: 'Philippines (the)',
    fullName: 'the Republic of the Philippines',
    alpha3: 'PHL',
    numericCode: '608',
  },
  {
    alpha2: 'PN',
    shortName: 'PITCAIRN',
    shortNameLowerCase: 'Pitcairn',
    fullName: '',
    alpha3: 'PCN',
    numericCode: '612',
  },
  {
    alpha2: 'PL',
    shortName: 'POLAND',
    shortNameLowerCase: 'Poland',
    fullName: 'the Republic of Poland',
    alpha3: 'POL',
    numericCode: '616',
  },
  {
    alpha2: 'PT',
    shortName: 'PORTUGAL',
    shortNameLowerCase: 'Portugal',
    fullName: 'the Portuguese Republic',
    alpha3: 'PRT',
    numericCode: '620',
  },
  {
    alpha2: 'PR',
    shortName: 'PUERTO RICO',
    shortNameLowerCase: 'Puerto Rico',
    fullName: '',
    alpha3: 'PRI',
    numericCode: '630',
  },
  {
    alpha2: 'QA',
    shortName: 'QATAR',
    shortNameLowerCase: 'Qatar',
    fullName: 'the State of Qatar',
    alpha3: 'QAT',
    numericCode: '634',
  },
  {
    alpha2: 'RO',
    shortName: 'ROMANIA',
    shortNameLowerCase: 'Romania',
    fullName: '',
    alpha3: 'ROU',
    numericCode: '642',
  },
  {
    alpha2: 'RU',
    shortName: 'RUSSIAN FEDERATION',
    shortNameLowerCase: 'Russian Federation (the)',
    fullName: 'the Russian Federation',
    alpha3: 'RUS',
    numericCode: '643',
  },
  {
    alpha2: 'RW',
    shortName: 'RWANDA',
    shortNameLowerCase: 'Rwanda',
    fullName: 'the Republic of Rwanda',
    alpha3: 'RWA',
    numericCode: '646',
  },
  {
    alpha2: 'RE',
    shortName: 'RÉUNION',
    shortNameLowerCase: 'Réunion',
    fullName: '',
    alpha3: 'REU',
    numericCode: '638',
  },
  {
    alpha2: 'BL',
    shortName: 'SAINT BARTHÉLEMY',
    shortNameLowerCase: 'Saint Barthélemy',
    fullName: '',
    alpha3: 'BLM',
    numericCode: '652',
  },
  {
    alpha2: 'SH',
    shortName: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    shortNameLowerCase: 'Saint Helena, Ascension and Tristan da Cunha',
    fullName: '',
    alpha3: 'SHN',
    numericCode: '654',
  },
  {
    alpha2: 'KN',
    shortName: 'SAINT KITTS AND NEVIS',
    shortNameLowerCase: 'Saint Kitts and Nevis',
    fullName: '',
    alpha3: 'KNA',
    numericCode: '659',
  },
  {
    alpha2: 'LC',
    shortName: 'SAINT LUCIA',
    shortNameLowerCase: 'Saint Lucia',
    fullName: '',
    alpha3: 'LCA',
    numericCode: '662',
  },
  {
    alpha2: 'MF',
    shortName: 'SAINT MARTIN (FRENCH PART)',
    shortNameLowerCase: 'Saint Martin (French part)',
    fullName: '',
    alpha3: 'MAF',
    numericCode: '663',
  },
  {
    alpha2: 'PM',
    shortName: 'SAINT PIERRE AND MIQUELON',
    shortNameLowerCase: 'Saint Pierre and Miquelon',
    fullName: '',
    alpha3: 'SPM',
    numericCode: '666',
  },
  {
    alpha2: 'VC',
    shortName: 'SAINT VINCENT AND THE GRENADINES',
    shortNameLowerCase: 'Saint Vincent and the Grenadines',
    fullName: '',
    alpha3: 'VCT',
    numericCode: '670',
  },
  {
    alpha2: 'WS',
    shortName: 'SAMOA',
    shortNameLowerCase: 'Samoa',
    fullName: 'the Independent State of Samoa',
    alpha3: 'WSM',
    numericCode: '882',
  },
  {
    alpha2: 'SM',
    shortName: 'SAN MARINO',
    shortNameLowerCase: 'San Marino',
    fullName: 'the Republic of San Marino',
    alpha3: 'SMR',
    numericCode: '674',
  },
  {
    alpha2: 'ST',
    shortName: 'SAO TOME AND PRINCIPE',
    shortNameLowerCase: 'Sao Tome and Principe',
    fullName: 'the Democratic Republic of Sao Tome and Principe',
    alpha3: 'STP',
    numericCode: '678',
  },
  {
    alpha2: 'SA',
    shortName: 'SAUDI ARABIA',
    shortNameLowerCase: 'Saudi Arabia',
    fullName: 'the Kingdom of Saudi Arabia',
    alpha3: 'SAU',
    numericCode: '682',
  },
  {
    alpha2: 'SN',
    shortName: 'SENEGAL',
    shortNameLowerCase: 'Senegal',
    fullName: 'the Republic of Senegal',
    alpha3: 'SEN',
    numericCode: '686',
  },
  {
    alpha2: 'RS',
    shortName: 'SERBIA',
    shortNameLowerCase: 'Serbia',
    fullName: 'the Republic of Serbia',
    alpha3: 'SRB',
    numericCode: '688',
  },
  {
    alpha2: 'SC',
    shortName: 'SEYCHELLES',
    shortNameLowerCase: 'Seychelles',
    fullName: 'the Republic of Seychelles',
    alpha3: 'SYC',
    numericCode: '690',
  },
  {
    alpha2: 'SL',
    shortName: 'SIERRA LEONE',
    shortNameLowerCase: 'Sierra Leone',
    fullName: 'the Republic of Sierra Leone',
    alpha3: 'SLE',
    numericCode: '694',
  },
  {
    alpha2: 'SG',
    shortName: 'SINGAPORE',
    shortNameLowerCase: 'Singapore',
    fullName: 'the Republic of Singapore',
    alpha3: 'SGP',
    numericCode: '702',
  },
  {
    alpha2: 'SX',
    shortName: 'SINT MAARTEN (DUTCH PART)',
    shortNameLowerCase: 'Sint Maarten (Dutch part)',
    fullName: '',
    alpha3: 'SXM',
    numericCode: '534',
  },
  {
    alpha2: 'SK',
    shortName: 'SLOVAKIA',
    shortNameLowerCase: 'Slovakia',
    fullName: 'the Slovak Republic',
    alpha3: 'SVK',
    numericCode: '703',
  },
  {
    alpha2: 'SI',
    shortName: 'SLOVENIA',
    shortNameLowerCase: 'Slovenia',
    fullName: 'the Republic of Slovenia',
    alpha3: 'SVN',
    numericCode: '705',
  },
  {
    alpha2: 'SB',
    shortName: 'SOLOMON ISLANDS',
    shortNameLowerCase: 'Solomon Islands',
    fullName: '',
    alpha3: 'SLB',
    numericCode: '090',
  },
  {
    alpha2: 'SO',
    shortName: 'SOMALIA',
    shortNameLowerCase: 'Somalia',
    fullName: 'the Federal Republic of Somalia',
    alpha3: 'SOM',
    numericCode: '706',
  },
  {
    alpha2: 'ZA',
    shortName: 'SOUTH AFRICA',
    shortNameLowerCase: 'South Africa',
    fullName: 'the Republic of South Africa',
    alpha3: 'ZAF',
    numericCode: '710',
  },
  {
    alpha2: 'GS',
    shortName: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    shortNameLowerCase: 'South Georgia and the South Sandwich Islands',
    fullName: '',
    alpha3: 'SGS',
    numericCode: '239',
  },
  {
    alpha2: 'SS',
    shortName: 'SOUTH SUDAN',
    shortNameLowerCase: 'South Sudan',
    fullName: 'the Republic of South Sudan',
    alpha3: 'SSD',
    numericCode: '728',
  },
  {
    alpha2: 'ES',
    shortName: 'SPAIN',
    shortNameLowerCase: 'Spain',
    fullName: 'the Kingdom of Spain',
    alpha3: 'ESP',
    numericCode: '724',
  },
  {
    alpha2: 'LK',
    shortName: 'SRI LANKA',
    shortNameLowerCase: 'Sri Lanka',
    fullName: 'the Democratic Socialist Republic of Sri Lanka',
    alpha3: 'LKA',
    numericCode: '144',
  },
  {
    alpha2: 'SD',
    shortName: 'SUDAN',
    shortNameLowerCase: 'Sudan (the)',
    fullName: 'the Republic of the Sudan',
    alpha3: 'SDN',
    numericCode: '729',
  },
  {
    alpha2: 'SR',
    shortName: 'SURINAME',
    shortNameLowerCase: 'Suriname',
    fullName: 'the Republic of Suriname',
    alpha3: 'SUR',
    numericCode: '740',
  },
  {
    alpha2: 'SJ',
    shortName: 'SVALBARD AND JAN MAYEN',
    shortNameLowerCase: 'Svalbard and Jan Mayen',
    fullName: '',
    alpha3: 'SJM',
    numericCode: '744',
  },
  {
    alpha2: 'SE',
    shortName: 'SWEDEN',
    shortNameLowerCase: 'Sweden',
    fullName: 'the Kingdom of Sweden',
    alpha3: 'SWE',
    numericCode: '752',
  },
  {
    alpha2: 'CH',
    shortName: 'SWITZERLAND',
    shortNameLowerCase: 'Switzerland',
    fullName: 'the Swiss Confederation',
    alpha3: 'CHE',
    numericCode: '756',
  },
  {
    alpha2: 'SY',
    shortName: 'SYRIAN ARAB REPUBLIC',
    shortNameLowerCase: 'Syrian Arab Republic (the)',
    fullName: 'the Syrian Arab Republic',
    alpha3: 'SYR',
    numericCode: '760',
  },
  {
    alpha2: 'TW',
    shortName: 'TAIWAN, PROVINCE OF CHINA',
    shortNameLowerCase: 'Taiwan (Province of China)',
    fullName: '',
    alpha3: 'TWN',
    numericCode: '158',
  },
  {
    alpha2: 'TJ',
    shortName: 'TAJIKISTAN',
    shortNameLowerCase: 'Tajikistan',
    fullName: 'the Republic of Tajikistan',
    alpha3: 'TJK',
    numericCode: '762',
  },
  {
    alpha2: 'TZ',
    shortName: 'TANZANIA, UNITED REPUBLIC OF',
    shortNameLowerCase: 'Tanzania, the United Republic of',
    fullName: 'the United Republic of Tanzania',
    alpha3: 'TZA',
    numericCode: '834',
  },
  {
    alpha2: 'TH',
    shortName: 'THAILAND',
    shortNameLowerCase: 'Thailand',
    fullName: 'the Kingdom of Thailand',
    alpha3: 'THA',
    numericCode: '764',
  },
  {
    alpha2: 'TL',
    shortName: 'TIMOR-LESTE',
    shortNameLowerCase: 'Timor-Leste',
    fullName: 'the Democratic Republic of Timor-Leste',
    alpha3: 'TLS',
    numericCode: '626',
  },
  {
    alpha2: 'TG',
    shortName: 'TOGO',
    shortNameLowerCase: 'Togo',
    fullName: 'the Togolese Republic',
    alpha3: 'TGO',
    numericCode: '768',
  },
  {
    alpha2: 'TK',
    shortName: 'TOKELAU',
    shortNameLowerCase: 'Tokelau',
    fullName: '',
    alpha3: 'TKL',
    numericCode: '772',
  },
  {
    alpha2: 'TO',
    shortName: 'TONGA',
    shortNameLowerCase: 'Tonga',
    fullName: 'the Kingdom of Tonga',
    alpha3: 'TON',
    numericCode: '776',
  },
  {
    alpha2: 'TT',
    shortName: 'TRINIDAD AND TOBAGO',
    shortNameLowerCase: 'Trinidad and Tobago',
    fullName: 'the Republic of Trinidad and Tobago',
    alpha3: 'TTO',
    numericCode: '780',
  },
  {
    alpha2: 'TN',
    shortName: 'TUNISIA',
    shortNameLowerCase: 'Tunisia',
    fullName: 'the Republic of Tunisia',
    alpha3: 'TUN',
    numericCode: '788',
  },
  {
    alpha2: 'TM',
    shortName: 'TURKMENISTAN',
    shortNameLowerCase: 'Turkmenistan',
    fullName: '',
    alpha3: 'TKM',
    numericCode: '795',
  },
  {
    alpha2: 'TC',
    shortName: 'TURKS AND CAICOS ISLANDS',
    shortNameLowerCase: 'Turks and Caicos Islands (the)',
    fullName: '',
    alpha3: 'TCA',
    numericCode: '796',
  },
  {
    alpha2: 'TV',
    shortName: 'TUVALU',
    shortNameLowerCase: 'Tuvalu',
    fullName: '',
    alpha3: 'TUV',
    numericCode: '798',
  },
  {
    alpha2: 'TR',
    shortName: 'TÜRKİYE',
    shortNameLowerCase: 'Türkiye',
    fullName: 'the Republic of Türkiye',
    alpha3: 'TUR',
    numericCode: '792',
  },
  {
    alpha2: 'UG',
    shortName: 'UGANDA',
    shortNameLowerCase: 'Uganda',
    fullName: 'the Republic of Uganda',
    alpha3: 'UGA',
    numericCode: '800',
  },
  {
    alpha2: 'UA',
    shortName: 'UKRAINE',
    shortNameLowerCase: 'Ukraine',
    fullName: '',
    alpha3: 'UKR',
    numericCode: '804',
  },
  {
    alpha2: 'AE',
    shortName: 'UNITED ARAB EMIRATES',
    shortNameLowerCase: 'United Arab Emirates (the)',
    fullName: 'the United Arab Emirates',
    alpha3: 'ARE',
    numericCode: '784',
  },
  {
    alpha2: 'GB',
    shortName: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND',
    shortNameLowerCase: 'United Kingdom of Great Britain and Northern Ireland (the)',
    fullName: 'the United Kingdom of Great Britain and Northern Ireland',
    alpha3: 'GBR',
    numericCode: '826',
  },
  {
    alpha2: 'UM',
    shortName: 'UNITED STATES MINOR OUTLYING ISLANDS',
    shortNameLowerCase: 'United States Minor Outlying Islands (the)',
    fullName: '',
    alpha3: 'UMI',
    numericCode: '581',
  },
  {
    alpha2: 'US',
    shortName: 'UNITED STATES OF AMERICA',
    shortNameLowerCase: 'United States of America (the)',
    fullName: 'the United States of America',
    alpha3: 'USA',
    numericCode: '840',
  },
  {
    alpha2: 'UY',
    shortName: 'URUGUAY',
    shortNameLowerCase: 'Uruguay',
    fullName: 'the Eastern Republic of Uruguay',
    alpha3: 'URY',
    numericCode: '858',
  },
  {
    alpha2: 'UZ',
    shortName: 'UZBEKISTAN',
    shortNameLowerCase: 'Uzbekistan',
    fullName: 'the Republic of Uzbekistan',
    alpha3: 'UZB',
    numericCode: '860',
  },
  {
    alpha2: 'VU',
    shortName: 'VANUATU',
    shortNameLowerCase: 'Vanuatu',
    fullName: 'the Republic of Vanuatu',
    alpha3: 'VUT',
    numericCode: '548',
  },
  {
    alpha2: 'VE',
    shortName: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    shortNameLowerCase: 'Venezuela (Bolivarian Republic of)',
    fullName: 'the Bolivarian Republic of Venezuela',
    alpha3: 'VEN',
    numericCode: '862',
  },
  {
    alpha2: 'VN',
    shortName: 'VIET NAM',
    shortNameLowerCase: 'Viet Nam',
    fullName: 'the Socialist Republic of Viet Nam',
    alpha3: 'VNM',
    numericCode: '704',
  },
  {
    alpha2: 'VG',
    shortName: 'VIRGIN ISLANDS (BRITISH)',
    shortNameLowerCase: 'Virgin Islands (British)',
    fullName: 'British Virgin Islands (the)',
    alpha3: 'VGB',
    numericCode: '092',
  },
  {
    alpha2: 'VI',
    shortName: 'VIRGIN ISLANDS (U.S.)',
    shortNameLowerCase: 'Virgin Islands (U.S.)',
    fullName: 'the Virgin Islands of the United States',
    alpha3: 'VIR',
    numericCode: '850',
  },
  {
    alpha2: 'WF',
    shortName: 'WALLIS AND FUTUNA',
    shortNameLowerCase: 'Wallis and Futuna',
    fullName: 'Wallis and Futuna Islands',
    alpha3: 'WLF',
    numericCode: '876',
  },
  {
    alpha2: 'EH',
    shortName: 'WESTERN SAHARA *',
    shortNameLowerCase: 'Western Sahara*',
    fullName: '',
    alpha3: 'ESH',
    numericCode: '732',
  },
  {
    alpha2: 'YE',
    shortName: 'YEMEN',
    shortNameLowerCase: 'Yemen',
    fullName: 'the Republic of Yemen',
    alpha3: 'YEM',
    numericCode: '887',
  },
  {
    alpha2: 'ZM',
    shortName: 'ZAMBIA',
    shortNameLowerCase: 'Zambia',
    fullName: 'the Republic of Zambia',
    alpha3: 'ZMB',
    numericCode: '894',
  },
  {
    alpha2: 'ZW',
    shortName: 'ZIMBABWE',
    shortNameLowerCase: 'Zimbabwe',
    fullName: 'the Republic of Zimbabwe',
    alpha3: 'ZWE',
    numericCode: '716',
  },
];
export default data;
