name: NPM Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN  }}
      - run: yarn build
      - name: Publish to NPM
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
